name: Auto PR

on: 
  push:
    branches: 'issue#*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Extract issue number from branch name
        run: |
          issue_number=$(echo "${GITHUB_REF_NAME}" | sed 's/[^0-9]*//g')
          echo "issue_number=$issue_number" >> $GITHUB_ENV  # Set the issue number as an environment variable
          echo "Extracted issue number: $issue_number"
    
      - name: create pull request
        env:
          ISSUE_NUMBER: ${{ env.issue_number }}
          BRANCH_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo -e "This is an automated pull request created by GitHub Actions Workflow of auto-pr.yml.\n\nSolving issue ${ISSUE_NUMBER}.\n\nBranch: ${BRANCH_NAME}" | \
          gh pr create \
            -B main \
            -H $BRANCH_NAME \
            --title "Auto PR from ${BRANCH_NAME} into main" \
            --body-file - \
            --label "automated"
                
# Multi line body
# Reference issue number in body
# Use variables
# With another branch