name: Auto PR

on: 
  push:
    branches: 'issue#*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Extract issue number from branch name
        run: |
          issue_number=$(echo "${GITHUB_REF_NAME}" | sed 's/[^0-9]*//g')
          echo "issue_number=$issue_number" >> $GITHUB_ENV  # Set the issue number as an environment variable
          echo "Extracted issue number: $issue_number"
    
      - name: Check if PR already exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if a PR already exists from the source branch to the target branch
          PR_EXISTS=$(gh pr list --head "${{ github.ref_name }}" --base main --json number --jq '. | length')
          echo "pr_exists=$PR_EXISTS" >> $GITHUB_ENV  # Set PR_EXISTS as an environment variable

      - name: Create or update pull request
        if: env.pr_exists == '0'  # Only run if no PR exists
        env:
          ISSUE_NUMBER: ${{ env.issue_number }}
          SOURCE_BRANCH_NAME: ${{ github.ref_name }}
          TARGET_BRANCH_NAME: main
          ASSIGNED_TO: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_TITLE=$(git log -1 --pretty=%B)
          echo -e "This is an automated pull request created by GitHub Actions Workflow defined in auto-pr.yml\n\nSolving issue #${ISSUE_NUMBER}\n\nSource Branch: ${SOURCE_BRANCH_NAME}\n\nTarget Branch: ${TARGET_BRANCH_NAME}\n\nAssigned To: ${ASSIGNED_TO}" | \
          gh pr create \
            -B $TARGET_BRANCH_NAME \
            -H $SOURCE_BRANCH_NAME \
            --title "${PR_TITLE} (Auto PR)" \
            --body-file - \
            --label "automated"

      - name: Add commit to existing PR
        if: env.pr_exists != '0'  # Only run if a PR already exists
        run: |
          echo "A pull request already exists for this branch. Adding the new commit to the existing PR."